name: Format

on:
    pull_request:
        paths:
            - "**.php"

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Install
              run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --optimize-autoloader --ignore-platform-reqs

            - name: Run php-cs-fixer
              run: ./vendor/bin/php-cs-fixer fix

            - uses: stefanzweifel/git-auto-commit-action@v2.1.0
              with:
                  commit_message: "style: resolve style guide violations"
                  branch: ${{ github.head_ref }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
